apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: three-tier-app
# Prevents K8s from mounting a JWT token at:
#   /var/run/secrets/kubernetes.io/serviceaccount/token
# That token can call the K8s API. Frontend has zero reason
# to call the API, so we remove the token entirely.
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: three-tier-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: three-tier-app
automountServiceAccountToken: false
